name: Sync GitHub to Bitbucket

on:
  workflow_dispatch:

jobs:
  check-bitbucket:
    runs-on: ubuntu-latest

    steps:
      - name: Check Bitbucket main
        env:
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
        run: |
          echo "GitHub commit:"
          echo "${{ github.sha }}"

          echo ""
          echo "Bitbucket main:"
          git ls-remote "https://x-token-auth:${BITBUCKET_TOKEN}@bitbucket.org/Simpalm/fintechnerdcon-backend.git" refs/heads/main